pipeline {
     agent { label 'agent'}
    
    environment {
        JAR_FILE = "java-sample-21-1.0.0.jar"
        APP_PORT = '5000'
    }
    
    // tools {
    //     maven 'Maven-3.9.0'
    //     jdk 'JDK-21'
    // }
    
    stages {
        stage('Checkout') {
            steps {
                echo '🔄 Checking out source code...'
                git branch: 'master', url: 'https://github.com/Pooja-chandrappa/jenkins.git'
            }
        }
        
    }

}
  
